#
# Copyright © 2021 The Authors
#
server:
  address: "${HTTP_BIND_ADDRESS:0.0.0.0}"
  port: "${HTTP_BIND_PORT:8080}"
  tomcat:
    connection-timeout: 60s
spring:
  application:
    name: cinema-service
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres_container}:5432/cinema
    username: cinema
    password: cinema
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:migration/initialRootChangeLog.xml

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml



