#
# Copyright © 2021 The Authors
#
server:
  address: "${HTTP_BIND_ADDRESS:0.0.0.0}"
  port: "${HTTP_BIND_PORT:8080}"
  tomcat:
    connection-timeout: 60s
spring:
  application:
    name: exampl-service
  profiles:
    active: sqllite
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


