#
# Copyright © 2021 The Akvelon Authors
#
version: "2.1"
services:
  postgres:
    container_name: postgres_container
    hostname: postgres_container
    image: postgres:11
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5432:5432"
    networks:
      - cinema-network
  cinema:
    image: eu.gcr.io/eminent-crane-329517/cinema:1.0-SNAPSHOT
    container_name: cinema-service
    hostname: cinema
    environment:
      HTTP_BIND_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    depends_on:
      - postgres
    networks:
      - cinema-network
networks:
  cinema-network:
    driver: bridge
